nodes:
  hosts:
    pve-01:
      ansible_host: 192.168.1.10 
      ansible_user: root
    pve-02:
      ansible_host: 192.168.1.11
      ansible_user: root
    pbs:
      ansible_host: 192.168.1.9
      ansible_user: root
pve:
  hosts:
    pve-01:
    pve-02:
vms:
  hosts:
    tailgate:
        ansible_user: example
        ansible_host: example.example.ts.net
